sudo: required
services:
  - docker

before_install:
  - docker build -t kri2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kri2/react-test npm test -- --coverage

after_success:
  - docker build -t kri2/multi-client ./client
  - docker build -t kri2/multi-nginx ./nginx
  - docker build -t kri2/multi-server ./server
  - docker build -t kri2/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push kri2/multi-client
  - docker push kri2/multi-nginx
  - docker push kri2/multi-server
  - docker push kri2/multi-worker